#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;

BIN=$PRE/usr/usr/bin;
DOC=$PRE/usr/share/doc/nps-ssh-askpass;

mkdir -p $BIN;
install -m755 nps-ssh-askpass $BIN;

mkdir -p $DOC;
cp README.md COPYING $DOC;
