name: nps-ssh-askpass
title: SSH Askpass
base: core20
version: "1.2.0"
#source-code: https://github.com/jafl/ssh-askpass
#issues: https://github.com/jafl/ssh-askpass/issues
#contact: https://johnlindal.wixsite.com/aboutme/contact-me
summary: Cross-platform replacement for x11-ssh-askpass.
description: |
  nps-ssh-askpass provides a cross-platform user interface for SSH
  to ask for a password.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el
  - build-on: s390x

apps:
  nps-ssh-askpass:
    command: bin/desktop-launch nps-ssh-askpass
#    environment:
#      XLOCALEDIR: $SNAP/usr/share/X11/locale
    plugs:
      - x11
      - desktop-legacy

parts:
  nps-ssh-askpass:
    plugin: autotools
    source: .
    disable-parallel: true
    build-environment:
      - JX_ROOT: /snap/jx-application-framework/current
      - PATH: $PATH:$JX_ROOT/bin
      - LD_LIBRARY_PATH: $SNAPCRAFT_PART_INSTALL/lib:$SNAPCRAFT_PART_INSTALL/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_PART_INSTALL/usr/lib:$SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    autotools-configure-parameters:
      - release
    stage:
      - bin/nps-ssh-askpass
    build-packages:
      - g++
      - make
      - pkg-config
      - libx11-dev
      - libxinerama-dev
      - libxft-dev
      - libxmu-dev
      - libxi-dev
      - libx11-xcb-dev
      - libxcb-xfixes0-dev
      - libxcb-dri2-0-dev
      - libxpm-dev
      - libjpeg-dev
      - libpng-dev
      - libgd-dev
      - libace-dev
      - libicu-dev
      - libpcre3-dev
      - libxml2-dev
      - xutils-dev
      - libdrm-dev
      - aspell
    build-snaps:
      - jx-application-framework
  libs:
    plugin: nil
    stage-packages:
      - libace-6.4.5
      - libfontconfig1
      - libfreetype6
      - libgd3
      - libicu66
      - libjbig0
      - libjpeg-turbo8
      - libpng16-16
      - libtiff5
      - libwebp6
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxinerama1
      - libxml2
      - libxpm4
      - libxrender1
  launcher:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
