name: CI
on:
  push:
    branches: [ main ]
    tags: [ v* ]
  repository_dispatch:
    types: [ new-jx ]
  workflow_dispatch:
jobs:
  build-ubuntu:
    name: -
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    uses: jafl/jx_application_framework/.github/workflows/app-build-ubuntu.yml@main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  build-ubuntu-release:
    name: -
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: jafl/jx_application_framework/.github/workflows/app-build-ubuntu-release.yml@main
    with:
      pkg-name: nps-ssh-askpass

  build-fedora:
    name: -
    uses: jafl/jx_application_framework/.github/workflows/app-build-fedora.yml@main
    with:
      pkg-name: nps-ssh-askpass

  build-macos:
    name: -
    uses: jafl/jx_application_framework/.github/workflows/app-build-macos.yml@main
    with:
      pkg-name: nps-ssh-askpass

  release:
    name: -
    needs: [ build-ubuntu-release, build-fedora, build-macos ]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: jafl/jx_application_framework/.github/workflows/app-release.yml@main
    with:
      pkg-name: nps-ssh-askpass
      forge-name: nps-ssh-askpass
    secrets:
      api-key: ${{ secrets.SOURCEFORGE_API_KEY }}
      ssh-key: ${{ secrets.SOURCEFORGE_SSH_KEY }}
